### ISSUE TITLE
OCRmyPDF not working on Python3.7.5?

### ISSUE THREAD

**Issue by AdrianButnar** [jbarlow83/OCRmyPDF#625]
I have installed it inside my WSL(Ubuntu) which runs Python 3.7.5 and I get the following error (on the run of a simple ```ocrmypdf input.pdf output.pdf```):
```
Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 11, in <module>
    load_entry_point('ocrmypdf==6.1.2', 'console_scripts', 'ocrmypdf')()
  File "/home/adrian/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 488, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/adrian/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2872, in load_entry_point
    return ep.load()
  File "/home/adrian/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/home/adrian/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/ocrmypdf/__main__.py", line 35, in <module>
    import ruffus.ruffus_exceptions as ruffus_exceptions
  File "/usr/lib/python3/dist-packages/ruffus/__init__.py", line 28, in <module>
    from .task import Pipeline, Task
  File "/usr/lib/python3/dist-packages/ruffus/task.py", line 715, in <module>
    verbose=0)
TypeError: namedtuple() got an unexpected keyword argument 'verbose'
```
I have seen that the verbose argument has been removed starting with Python 3.7, but the requirements list specifies that Python 3.6+ is ok.

Thank you for taking the time to look at this!

**Comment by jbarlow83** [comment]
That's an old version of ocrmypdf. There's a detailed install procedure to
get the latest version.

I think you have Ubuntu 18.04 WSL, based on ocrmypdf 6.1.2. If so, that
means you installed Python 3.7 from some other source, based on the
$HOME/.local/lib paths. There's something quite wrong with that 3.7
install, because it's reaching inside /usr/lib/python3 which should contain
only the system Python 3.6. I'm not sure how you got this, but it looks
like it is a broken install that is going to cause endless problems with
any software outside the standard library.

**Comment by jbarlow83** [comment]
I'll close the issue now. If you have further related questions feel free to reopen it.

**Comment by jdegange** [comment]
This issue persists in March 2022 on Py3.7 using the latest install instructions in `OCRmyPDF/readme.md` on Linux. Any resolution?

~~~shell 
Traceback (most recent call last):
  File "/usr/bin/ocrmypdf", line 11, in <module>
    load_entry_point('ocrmypdf==6.1.2', 'console_scripts', 'ocrmypdf')()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2846, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/ocrmypdf/__main__.py", line 35, in <module>
    import ruffus.ruffus_exceptions as ruffus_exceptions
  File "/usr/lib/python3/dist-packages/ruffus/__init__.py", line 28, in <module>
    from .task import Pipeline, Task
  File "/usr/lib/python3/dist-packages/ruffus/task.py", line 715, in <module>
    verbose=0)
TypeError: namedtuple() got an unexpected keyword argument 'verbose'
~~~

**Comment by jbarlow83** [comment]
Yes, the resolution is to upgrade to a newer version of ocrmypdf. Version 6.1.2 is 7 major releases ago.
